/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Website blocker API Documentation
 * OpenAPI spec version: 1.0.0
 */
import { createApiInstance } from './api-instance';
import type { BodyType } from './api-instance';
export interface HelloWorldDto {
  message: string;
}

export interface AccountDto {
  id: number;
  isBlockingEnabled: boolean;
  ownerId: number;
}

export interface PatchAccountDto {
  isBlockingEnabled?: boolean;
}

export type BlockItemDtoType = typeof BlockItemDtoType[keyof typeof BlockItemDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BlockItemDtoType = {
  WEBSITE: 'WEBSITE',
  KEYWORD: 'KEYWORD',
} as const;

export interface BlockItemDto {
  id: number;
  blockListId: number;
  type: BlockItemDtoType;
  data: string;
  createdAt: string;
}

export interface BlockListDto {
  id: number;
  ownerId: number;
  items: BlockItemDto[];
}

export type AddBlockItemDtoType = typeof AddBlockItemDtoType[keyof typeof AddBlockItemDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddBlockItemDtoType = {
  WEBSITE: 'WEBSITE',
  KEYWORD: 'KEYWORD',
} as const;

export interface AddBlockItemDto {
  type: AddBlockItemDtoType;
  data: string;
}

export interface SignInBodyDto {
  email: string;
  password: string;
}

export interface SignUpBodyDto {
  email: string;
  password: string;
}

export interface GetSessionInfoDto {
  id: number;
  email: string;
  iat: number;
  exp: number;
}

export type BlockListControllerGetBlockListParams = {
/**
 * @nullable
 */
q?: string | null;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const appControllerGetHello = (
    
 options?: SecondParameter<typeof createApiInstance<HelloWorldDto>>,) => {
      return createApiInstance<HelloWorldDto>(
      {url: `/`, method: 'GET'
    },
      options);
    }
  
export const accountControllerGetAccountInfo = (
    
 options?: SecondParameter<typeof createApiInstance<AccountDto>>,) => {
      return createApiInstance<AccountDto>(
      {url: `/account`, method: 'GET'
    },
      options);
    }
  
export const accountControllerPatchAccount = (
    patchAccountDto: BodyType<PatchAccountDto>,
 options?: SecondParameter<typeof createApiInstance<AccountDto>>,) => {
      return createApiInstance<AccountDto>(
      {url: `/account`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchAccountDto
    },
      options);
    }
  
export const blockListControllerGetBlockList = (
    params?: BlockListControllerGetBlockListParams,
 options?: SecondParameter<typeof createApiInstance<BlockListDto>>,) => {
      return createApiInstance<BlockListDto>(
      {url: `/block-list`, method: 'GET',
        params
    },
      options);
    }
  
export const blockListControllerGetBlockItem = (
    id: number,
 options?: SecondParameter<typeof createApiInstance<BlockItemDto>>,) => {
      return createApiInstance<BlockItemDto>(
      {url: `/block-list/item/${id}`, method: 'GET'
    },
      options);
    }
  
export const blockListControllerRemoveBlockItem = (
    id: number,
 options?: SecondParameter<typeof createApiInstance<void>>,) => {
      return createApiInstance<void>(
      {url: `/block-list/item/${id}`, method: 'DELETE'
    },
      options);
    }
  
export const blockListControllerAddBlockItem = (
    addBlockItemDto: BodyType<AddBlockItemDto>,
 options?: SecondParameter<typeof createApiInstance<BlockItemDto>>,) => {
      return createApiInstance<BlockItemDto>(
      {url: `/block-list/item`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addBlockItemDto
    },
      options);
    }
  
export const authControllerSignIn = (
    signInBodyDto: BodyType<SignInBodyDto>,
 options?: SecondParameter<typeof createApiInstance<void>>,) => {
      return createApiInstance<void>(
      {url: `/auth/signin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signInBodyDto
    },
      options);
    }
  
export const authControllerSignUp = (
    signUpBodyDto: BodyType<SignUpBodyDto>,
 options?: SecondParameter<typeof createApiInstance<void>>,) => {
      return createApiInstance<void>(
      {url: `/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signUpBodyDto
    },
      options);
    }
  
export const authControllerSignOut = (
    
 options?: SecondParameter<typeof createApiInstance<void>>,) => {
      return createApiInstance<void>(
      {url: `/auth/signout`, method: 'POST'
    },
      options);
    }
  
export const authControllerGetSessionInfo = (
    
 options?: SecondParameter<typeof createApiInstance<GetSessionInfoDto>>,) => {
      return createApiInstance<GetSessionInfoDto>(
      {url: `/auth/session-info`, method: 'POST'
    },
      options);
    }
  
export type AppControllerGetHelloResult = NonNullable<Awaited<ReturnType<typeof appControllerGetHello>>>
export type AccountControllerGetAccountInfoResult = NonNullable<Awaited<ReturnType<typeof accountControllerGetAccountInfo>>>
export type AccountControllerPatchAccountResult = NonNullable<Awaited<ReturnType<typeof accountControllerPatchAccount>>>
export type BlockListControllerGetBlockListResult = NonNullable<Awaited<ReturnType<typeof blockListControllerGetBlockList>>>
export type BlockListControllerGetBlockItemResult = NonNullable<Awaited<ReturnType<typeof blockListControllerGetBlockItem>>>
export type BlockListControllerRemoveBlockItemResult = NonNullable<Awaited<ReturnType<typeof blockListControllerRemoveBlockItem>>>
export type BlockListControllerAddBlockItemResult = NonNullable<Awaited<ReturnType<typeof blockListControllerAddBlockItem>>>
export type AuthControllerSignInResult = NonNullable<Awaited<ReturnType<typeof authControllerSignIn>>>
export type AuthControllerSignUpResult = NonNullable<Awaited<ReturnType<typeof authControllerSignUp>>>
export type AuthControllerSignOutResult = NonNullable<Awaited<ReturnType<typeof authControllerSignOut>>>
export type AuthControllerGetSessionInfoResult = NonNullable<Awaited<ReturnType<typeof authControllerGetSessionInfo>>>
